language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_install:
  - npm install -g npm
  - npm install -g poltergeist
  - npm install -g webpack
  - npm install -g bower
  - gem install bundler
  - bundle install
  - npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - rake
