language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
install:
  - nvm install 6.3
  - nvm use 6.3
  - npm install -g webpack
  - npm install -g bower
  - bundle install
  - npm install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - DRIVER=selenium_firefox bundle exec rake
